### ISSUE TITLE
react-sidebar-pro is not working as shown in the video tutorial anymore

### ISSUE THREAD

**Issue by i-m-abbhay** [ed-roh/react-admin-dashboard#16]
I am trying to use react-sidebar-pro, but it is not working as shown in the video tutorial. I have followed the instructions in the tutorial, but having the issue "Module not found: Error: Can't resolve 'react-pro-sidebar/dist/css/styles.css'". I have also tried to comeup with the solution but I wasn't able to implement the new version of the sidebar.

I would appreciate it if you could push an update to the existing code or please suggest me the way to resolve it. I will try to do it on my own and will be happy to contribute to your code.

Thank you for your time.

**Comment by hammadkhan** [comment]
@i-m-abbhay Do you mind sharing the solution with others so it can help them? Just closing is not very helpful.

**Comment by i-m-abbhay** [comment]
> @i-m-abbhay Do you mind sharing the solution with others so it can help them? Just closing is not very helpful.

Yeah Sure!
For now I've used his package.json.lock file to download the exact same versions of all the packages that were used in the tutorial.

**Comment by hammadkhan** [comment]
Yes, that's the solution. You have to run the entire project as it is. You can't start your own project, then copy the code and expect it to run successfully.
